### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/dockwater#12]
I updated my Ubuntu 18.04 machine which seems to have broken my nvidia docker setup with gazebo.

### Noetic

* I build the `noetic` image: `./build.sh noetic`, 
* start the container: `./run.py noetic:latest`
* then inside the container run `gazebo`, generates the following error
```
bsb@deeff81bdbdb:~$ gazebo
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

### Melodic

Similarly in the melodic container

```
bsb@f1e4a8ce1b06:~$ gazebo
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  38
  Current serial number in output stream:  37
```

## Clues

Ran out of time to debug, but looking at these threads:

* https://stackoverflow.com/questions/66231993/gazebo-and-rviz-in-docker-stopped-working-after-installing-nvidia
* http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration#nvidia-docker2

**Comment by bsb808** [comment]
@M1chaelM - have you seen this before?

**Comment by bsb808** [comment]
This didn't work...

Tried the recommendation [here](http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration#nvidia-docker2) and added the following to the Dockerfile

```
# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics
```

**Comment by bsb808** [comment]
I updated all my nvidia drivers - currently running `nvidia-driver-470/`

The libGL errors seem to be gone, but when starting gazebo still getting...
```
bsb@5f29ddd71fb3:~$ gazebo
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
```

**Comment by M1chaelM** [comment]
@bsb808 No, I haven't seen that random generator error before. 

I *have* seen the Nvidia error sometimes briefly after updating a driver. I'm not 100% sure but I think it can be caused when you have installed a newer version of the Nvidia driver but have not actually switched over to using it yet. My memory was that it was resolved by rebooting.

I don't think the random generator error and the Nvidia issue are related. What hardware are you running on?

**Comment by bsb808** [comment]
Thank you.  I'll work on it tomorrow

**Comment by M1chaelM** [comment]
@bsb808 was this issue ever resolved?

**Comment by j-herman** [comment]
@M1chaelM I saw the random number generator error last year - believe I had to update BIOS to resolve it.  Until I did, my random numbers were not random.  It has been a while so I may have forgotten some details, but I do not think this was an issue with docker.
