### ISSUE TITLE
Is it possible to start without rocker?

### ISSUE THREAD

**Issue by ForceConstant** [Field-Robotics-Lab/dockwater#14]
I am trying to run the cuda version, but am inside a lab that doesn't have easy access to internet, so all the dynamically built dockerfiles fail using rocker. Is it possible to run without rocker?

Thanks

**Comment by mabelzhang** [comment]
Short answer is yes, you can run without rocker. You'll have a root user and have to specify all the flags that rocker specify for you yourself. So all the flags in `ROCKER_ARGS` in `run.bash`, look for what rocker does for them, and specify those manually to `docker run`.

**Comment by bsb808** [comment]
Closing as resolved - feel free to reopen if more conversation is needed.
